<a href="https://colab.research.google.com/github/mademet/DAwPY/blob/main/np_indexing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns


<function seaborn.utils.load_dataset>

In [4]:
df = sns.load_dataset("diamonds")

In [5]:
df

carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [15]:
dm = np.array(df[["carat", "depth", "price", "x", "y", "z"]], dtype= "float")
dm

array([[2.300e-01, 6.150e+01, 3.260e+02, 3.950e+00, 3.980e+00, 2.430e+00],
       [2.100e-01, 5.980e+01, 3.260e+02, 3.890e+00, 3.840e+00, 2.310e+00],
       [2.300e-01, 5.690e+01, 3.270e+02, 4.050e+00, 4.070e+00, 2.310e+00],
       ...,
       [7.000e-01, 6.280e+01, 2.757e+03, 5.660e+00, 5.680e+00, 3.560e+00],
       [8.600e-01, 6.100e+01, 2.757e+03, 6.150e+00, 6.120e+00, 3.740e+00],
       [7.500e-01, 6.220e+01, 2.757e+03, 5.830e+00, 5.870e+00, 3.640e+00]])

In [16]:
dm[0:2]

array([[2.30e-01, 6.15e+01, 3.26e+02, 3.95e+00, 3.98e+00, 2.43e+00],
       [2.10e-01, 5.98e+01, 3.26e+02, 3.89e+00, 3.84e+00, 2.31e+00]])

In [17]:
dm[0]

array([2.30e-01, 6.15e+01, 3.26e+02, 3.95e+00, 3.98e+00, 2.43e+00])

In [18]:
dm[:3]

array([[2.30e-01, 6.15e+01, 3.26e+02, 3.95e+00, 3.98e+00, 2.43e+00],
       [2.10e-01, 5.98e+01, 3.26e+02, 3.89e+00, 3.84e+00, 2.31e+00],
       [2.30e-01, 5.69e+01, 3.27e+02, 4.05e+00, 4.07e+00, 2.31e+00]])

In [19]:
dm[0:2, 0:3]

array([[2.30e-01, 6.15e+01, 3.26e+02],
       [2.10e-01, 5.98e+01, 3.26e+02]])

In [21]:
dm[0:2]

array([[2.30e-01, 6.15e+01, 3.26e+02, 3.95e+00, 3.98e+00, 2.43e+00],
       [2.10e-01, 5.98e+01, 3.26e+02, 3.89e+00, 3.84e+00, 2.31e+00]])

In [24]:
carat = dm[:,0].reshape(-1, 1)
carat

array([[0.23],
       [0.21],
       [0.23],
       ...,
       [0.7 ],
       [0.86],
       [0.75]])

In [25]:
depth = dm[:,1].reshape(-1, 1)
depth

array([[61.5],
       [59.8],
       [56.9],
       ...,
       [62.8],
       [61. ],
       [62.2]])

In [26]:
np.concatenate([carat, depth], axis = 1)

array([[ 0.23, 61.5 ],
       [ 0.21, 59.8 ],
       [ 0.23, 56.9 ],
       ...,
       [ 0.7 , 62.8 ],
       [ 0.86, 61.  ],
       [ 0.75, 62.2 ]])

In [27]:
x = dm[:,-3].reshape(-1, 1)
y = dm[:,-2].reshape(-1, 1)
z = dm[:,-1].reshape(-1, 1)

In [28]:
xyz = np.concatenate([x, y, z], axis = 1)
xyz

array([[3.95, 3.98, 2.43],
       [3.89, 3.84, 2.31],
       [4.05, 4.07, 2.31],
       ...,
       [5.66, 5.68, 3.56],
       [6.15, 6.12, 3.74],
       [5.83, 5.87, 3.64]])

In [31]:
volume = x * y * z

In [32]:
task = np.concatenate([xyz, volume], axis = 1)
task

array([[  3.95    ,   3.98    ,   2.43    ,  38.20203 ],
       [  3.89    ,   3.84    ,   2.31    ,  34.505856],
       [  4.05    ,   4.07    ,   2.31    ,  38.076885],
       ...,
       [  5.66    ,   5.68    ,   3.56    , 114.449728],
       [  6.15    ,   6.12    ,   3.74    , 140.76612 ],
       [  5.83    ,   5.87    ,   3.64    , 124.568444]])

In [33]:
a2 = np.arange(1, 10).reshape(3, 3)
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
print(a2[:1])

[[1 2 3]]


In [35]:
print(a2[:, 1])

[2 5 8]


In [38]:
arr = np.arange(10, 30).reshape(4,5)
arr[1:,2:4]

array([[17, 18],
       [22, 23],
       [27, 28]])

In [63]:
arr[1:4,2:4]

array([[17, 18],
       [22, 23],
       [27, 28]])