<a href="https://colab.research.google.com/github/mademet/DAwPY/blob/main/numpy/np_concat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
ones = np.ones((4, 4), dtype= "int")
ones

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
rand = np.random.randint(2, 10, size = (4, 4))
rand

array([[6, 8, 8, 9],
       [5, 2, 8, 5],
       [8, 2, 3, 2],
       [6, 9, 5, 7]])

In [ ]:
concat = np.concatenate([ones, rand])
concat

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [6, 8, 8, 9],
       [5, 2, 8, 5],
       [8, 2, 3, 2],
       [6, 9, 5, 7]])

In [ ]:
concat = np.concatenate([ones, rand], axis = 1)
concat

array([[1, 1, 1, 1, 6, 8, 8, 9],
       [1, 1, 1, 1, 5, 2, 8, 5],
       [1, 1, 1, 1, 8, 2, 3, 2],
       [1, 1, 1, 1, 6, 9, 5, 7]])

In [ ]:
np.split(concat, 4)

[array([[1, 1, 1, 1, 6, 8, 8, 9]]),
 array([[1, 1, 1, 1, 5, 2, 8, 5]]),
 array([[1, 1, 1, 1, 8, 2, 3, 2]]),
 array([[1, 1, 1, 1, 6, 9, 5, 7]])]

In [ ]:
c2 = np.split(concat, [1, 3], axis = 1)
for i in c2:
    print(i)  # 0 to 1, 1 to 3, 3 to end

[[1]
 [1]
 [1]
 [1]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]]
[[1 6 8 8 9]
 [1 5 2 8 5]
 [1 8 2 3 2]
 [1 6 9 5 7]]
